"""This module contains the character data information."""
from pydantic import BaseModel


class CharacterInput(BaseModel):
    """Character data model."""

    name: str
    url_path: str | None = None


characters: list[CharacterInput] = [
    CharacterInput(name="Kamisato Ayaka"),
    CharacterInput(name="Jean"),
    CharacterInput(name="Traveler (Anemo)"),
    CharacterInput(name="Traveler (Geo)"),
    CharacterInput(name="Traveler (Electro)"),
    CharacterInput(name="Traveler (Dendro)"),
    CharacterInput(name="Traveler (Hydro)"),
    CharacterInput(name="Lisa"),
    CharacterInput(name="Barbara"),
    CharacterInput(name="Kaeya"),
    CharacterInput(name="Diluc"),
    CharacterInput(name="Razor"),
    CharacterInput(name="Amber"),
    CharacterInput(name="Venti"),
    CharacterInput(name="Xiangling"),
    CharacterInput(name="Beidou"),
    CharacterInput(name="Xingqiu"),
    CharacterInput(name="Xiao"),
    CharacterInput(name="Ningguang"),
    CharacterInput(name="Klee"),
    CharacterInput(name="Zhongli"),
    CharacterInput(name="Fischl"),
    CharacterInput(name="Bennett"),
    CharacterInput(name="Tartaglia"),
    CharacterInput(name="Noelle"),
    CharacterInput(name="Qiqi"),
    CharacterInput(name="Chongyun"),
    CharacterInput(name="Ganyu"),
    CharacterInput(name="Albedo"),
    CharacterInput(name="Diona"),
    CharacterInput(name="Mona"),
    CharacterInput(name="Keqing"),
    CharacterInput(name="Sucrose"),
    CharacterInput(name="Xinyan"),
    CharacterInput(name="Rosaria"),
    CharacterInput(name="Hu Tao"),
    CharacterInput(name="Kaedehara Kazuha"),
    CharacterInput(name="Yanfei"),
    CharacterInput(name="Yoimiya"),
    CharacterInput(name="Thoma"),
    CharacterInput(name="Eula"),
    CharacterInput(name="Raiden Shogun"),
    CharacterInput(name="Sayu"),
    CharacterInput(name="Sangonomiya Kokomi"),
    CharacterInput(name="Gorou"),
    CharacterInput(name="Kujou Sara"),
    CharacterInput(name="Arataki Itto"),
    CharacterInput(name="Yae Miko"),
    CharacterInput(name="Shikanoin Heizou"),
    CharacterInput(name="Yelan"),
    CharacterInput(name="Kirara"),
    CharacterInput(name="Aloy"),
    CharacterInput(name="Shenhe"),
    CharacterInput(name="Yun Jin"),
    CharacterInput(name="Kuki Shinobu"),
    CharacterInput(name="Kamisato Ayato"),
    CharacterInput(name="Collei"),
    CharacterInput(name="Dori"),
    CharacterInput(name="Tighnari"),
    CharacterInput(name="Nilou"),
    CharacterInput(name="Cyno"),
    CharacterInput(name="Candace"),
    CharacterInput(name="Nahida"),
    CharacterInput(name="Layla"),
    CharacterInput(name="Wanderer"),
    CharacterInput(name="Faruzan"),
    CharacterInput(name="Yaoyao"),
    CharacterInput(name="Alhaitham"),
    CharacterInput(name="Dehya"),
    CharacterInput(name="Mika"),
    CharacterInput(name="Kaveh"),
    CharacterInput(name="Baizhu"),
    CharacterInput(name="Lynette"),
    CharacterInput(name="Lyney"),
    CharacterInput(name="Freminet"),
    CharacterInput(name="Wriothesley"),
    CharacterInput(name="Neuvillette"),
    CharacterInput(name="Charlotte"),
    CharacterInput(name="Furina"),
    CharacterInput(name="Chevreuse"),
    CharacterInput(name="Navia"),
]
